spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tianqi?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      #更新或者创建数据表
      ddl-auto: update
    show-sql: false


server:
  port: 8081
